### ISSUE TITLE
Update readme to reflect new CRC recipes

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/jupyterhub-docker#2]
PR #1 heavily modified the Docker and compose recipes. However, it did not update the project README. The README needs updating to reflect these changes. Instructions should also be included for tearing down the recipe with Podman while avoiding the networking bugs where processes iare not terminated properly.

**Comment by yassinkhalifa** [comment]
@djperrefort I will update that when we finalize everything about the deployment.
