### ISSUE TITLE
Impliment/verfiy support for user virtual environments

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/jupyterhub-docker#3]
We want users to be able to use virtual environments within the containerized jupyterlab sessions. This feature needs implementation and testing.

**Comment by yassinkhalifa** [comment]
@djperrefort I tested the support of virtual environments through a conda package called "[nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels)" that manages kernels. Through this package, whenever the user  creates a new conda env (e.g.: conda create -n test_env python=3.10 ipykernel), it will be automatically added as a kernel and they can change the notebook kernel to it. I am working here on the assumption that each user is spawned a separate jupyterlab container from the others, does this make sense? Please take a look on the branch and let me know what you think, it's currently up and you can test it.

**Comment by djperrefort** [comment]
@yassinkhalifa Can I close this issue or are you still working on the VE support?

**Comment by yassinkhalifa** [comment]
Yes, please go ahead and close it. I already tested that and hopefully it continues to work as expected.
